name: Pull Request

on:
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
      - name: Install dependencies
        run: npm install pnpm -g  && pnpm install --frozen-lockfile
      - name: Lint
        run: npm run lint

  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
      - name: Install dependencies
        run: npm install pnpm -g  && pnpm install --frozen-lockfile
      - name: Test
        run: npm run test:unit

  
  e2e_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install pnpm -g && pnpm install
      - name: Test
        run: npm run test:e2e