name: Release

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install pnpm -g && pnpm install
      - name: Lint
        run: npm run lint

  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install pnpm -g && pnpm install
      - name: Test
        run: npm run test:unit

  e2e_test:
    runs-on: ubuntu-latest
    needs: [unit_test]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install pnpm -g && pnpm install
      - name: Test
        run: npm run test:e2e

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, unit_test, e2e_test]
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install pnpm -g && pnpm install
      - name: Build
        run: npm run build
      - name: Deploy
        run: npm run deploy